export const PERMISSIONS = {
  USERS_VIEW: "USERS_VIEW",
  USERS_EDIT: "USERS_EDIT",
  USERS_SUSPEND: "USERS_SUSPEND",
  CIRCLES_VIEW: "CIRCLES_VIEW",
  CIRCLES_EDIT: "CIRCLES_EDIT",
  REVENUE_VIEW: "REVENUE_VIEW",
  REVENUE_EXPORT: "REVENUE_EXPORT",
  PLATFORM_SETTINGS_EDIT: "PLATFORM_SETTINGS_EDIT",
  ADMINS_MANAGE: "ADMINS_MANAGE",
  SUPPORT_MANAGE: "SUPPORT_MANAGE",
  FRAUD_REVIEW: "FRAUD_REVIEW",
  BROADCAST_SEND: "BROADCAST_SEND",
  PLANS_MANAGE: "PLANS_MANAGE",
  PROMOS_MANAGE: "PROMOS_MANAGE",
  BULK_OPERATIONS_RUN: "BULK_OPERATIONS_RUN",
  PAYMENTS_VIEW: "PAYMENTS_VIEW",
  PAYMENTS_EDIT: "PAYMENTS_EDIT",
  SUBSCRIPTIONS_VIEW: "SUBSCRIPTIONS_VIEW",
  SUBSCRIPTIONS_EDIT: "SUBSCRIPTIONS_EDIT",
  WALLETS_VIEW: "WALLETS_VIEW",
  VERIFICATIONS_MANAGE: "VERIFICATIONS_MANAGE",
  DISCOVER_MANAGE: "DISCOVER_MANAGE",
  MODERATION_REVIEW: "MODERATION_REVIEW",
  ANALYTICS_VIEW: "ANALYTICS_VIEW",
  AUDIT_LOGS_VIEW: "AUDIT_LOGS_VIEW",
} as const

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  SUPER_ADMIN: ["*"],
  ADMIN: [
    "USERS_VIEW", "USERS_EDIT",
    "CIRCLES_VIEW", "CIRCLES_EDIT",
    "SUBSCRIPTIONS_VIEW", "SUBSCRIPTIONS_EDIT",
    "PAYMENTS_VIEW", "PAYMENTS_EDIT",
    "SUPPORT_MANAGE", "MODERATION_REVIEW",
    "VERIFICATIONS_MANAGE",
    "BROADCAST_SEND",
    "PLANS_MANAGE", "PROMOS_MANAGE",
    "ANALYTICS_VIEW", "AUDIT_LOGS_VIEW",
    "DISCOVER_MANAGE", "FRAUD_REVIEW",
  ],
  SUPPORT: [
    "USERS_VIEW", "CIRCLES_VIEW",
    "PAYMENTS_VIEW",
    "SUPPORT_MANAGE", "MODERATION_REVIEW",
    "VERIFICATIONS_MANAGE",
  ],
  FINANCE: [
    "SUBSCRIPTIONS_VIEW", "SUBSCRIPTIONS_EDIT",
    "PAYMENTS_VIEW", "PAYMENTS_EDIT",
    "REVENUE_VIEW", "REVENUE_EXPORT",
    "WALLETS_VIEW",
    "ANALYTICS_VIEW",
  ],
}

export function canPerform(role: string, action: string): boolean {
  const allowed = ROLE_PERMISSIONS[role] || []
  if (allowed.includes("*")) return true
  return allowed.some((a) => action === a)
}
