export const CIRCLE_PERMISSIONS = {
  // Circle management
  CIRCLE_VIEW: "CIRCLE_VIEW",
  CIRCLE_UPDATE: "CIRCLE_UPDATE",
  CIRCLE_DELETE: "CIRCLE_DELETE",
  SETTINGS_MANAGE: "SETTINGS_MANAGE",

  // Member management
  MEMBER_VIEW: "MEMBER_VIEW",
  MEMBER_INVITE: "MEMBER_INVITE",
  MEMBER_REMOVE: "MEMBER_REMOVE",
  MEMBER_ROLE_UPDATE: "MEMBER_ROLE_UPDATE",
  MEMBER_PERMISSION_MANAGE: "MEMBER_PERMISSION_MANAGE",
  MEMBER_AUDIT_VIEW: "MEMBER_AUDIT_VIEW",

  // Contributions
  CONTRIBUTION_CREATE: "CONTRIBUTION_CREATE",
  CONTRIBUTION_SUBMIT_OWN: "CONTRIBUTION_SUBMIT_OWN",
  CONTRIBUTION_VIEW_OWN: "CONTRIBUTION_VIEW_OWN",
  CONTRIBUTION_VIEW_ALL: "CONTRIBUTION_VIEW_ALL",
  CONTRIBUTION_REVIEW: "CONTRIBUTION_REVIEW",
  CONTRIBUTION_REJECT: "CONTRIBUTION_REJECT",
  CONTRIBUTION_REFUND: "CONTRIBUTION_REFUND",
  SCHEDULE_MANAGE: "SCHEDULE_MANAGE",
  SCHEDULE_VIEW: "SCHEDULE_VIEW",

  // Expenses
  EXPENSE_CREATE: "EXPENSE_CREATE",
  EXPENSE_VIEW: "EXPENSE_VIEW",
  EXPENSE_APPROVE: "EXPENSE_APPROVE",
  EXPENSE_DELETE: "EXPENSE_DELETE",

  // Settlements
  SETTLEMENT_CREATE: "SETTLEMENT_CREATE",
  SETTLEMENT_VIEW: "SETTLEMENT_VIEW",
  SETTLEMENT_CONFIRM: "SETTLEMENT_CONFIRM",

  // Goals
  GOAL_CREATE: "GOAL_CREATE",
  GOAL_UPDATE: "GOAL_UPDATE",
  GOAL_DELETE: "GOAL_DELETE",

  // Ledger
  LEDGER_VIEW: "LEDGER_VIEW",
  LEDGER_ADJUST: "LEDGER_ADJUST",

  // Reports
  REPORT_VIEW: "REPORT_VIEW",
  REPORT_EXPORT: "REPORT_EXPORT",

  // AI / Financial Insights
  AI_VIEW: "AI_VIEW",
  AI_MANAGE: "AI_MANAGE",

  // Projects
  PROJECT_CREATE: "PROJECT_CREATE",
  PROJECT_VIEW: "PROJECT_VIEW",
  PROJECT_MANAGE: "PROJECT_MANAGE",
  PROJECT_APPROVE: "PROJECT_APPROVE",

  // Project Funding
  FUNDING_ROUND_CREATE: "FUNDING_ROUND_CREATE",
  FUNDING_ALLOCATION_MANAGE: "FUNDING_ALLOCATION_MANAGE",
  FUNDING_RECORD: "FUNDING_RECORD",
  SHORTFALL_MANAGE: "SHORTFALL_MANAGE",
  INVESTOR_MANAGE: "INVESTOR_MANAGE",
  OWNERSHIP_VIEW: "OWNERSHIP_VIEW",
  OWNERSHIP_MANAGE: "OWNERSHIP_MANAGE",
  REVENUE_MANAGE: "REVENUE_MANAGE",
  DISTRIBUTION_CREATE: "DISTRIBUTION_CREATE",
  DISTRIBUTION_APPROVE: "DISTRIBUTION_APPROVE",

  // Project Expenses
  PROJECT_EXPENSE_VIEW: "PROJECT_EXPENSE_VIEW",
  PROJECT_EXPENSE_CREATE: "PROJECT_EXPENSE_CREATE",
  PROJECT_EXPENSE_EDIT: "PROJECT_EXPENSE_EDIT",
  PROJECT_EXPENSE_APPROVE: "PROJECT_EXPENSE_APPROVE",
  PROJECT_EXPENSE_VOID: "PROJECT_EXPENSE_VOID",
  PROJECT_EXPENSE_DELETE: "PROJECT_EXPENSE_DELETE",

  // Wallets / Payouts
  WALLET_VIEW: "WALLET_VIEW",
  PAYOUT_REQUEST: "PAYOUT_REQUEST",
  PAYOUT_APPROVE: "PAYOUT_APPROVE",
  PAYOUT_CONFIGURE: "PAYOUT_CONFIGURE",
  PAYOUT_MANAGE: "PAYOUT_MANAGE",
  PAYOUT_VIEW_ALL: "PAYOUT_VIEW_ALL",
  PAYOUT_SUBMIT: "PAYOUT_SUBMIT",
  PAYOUT_RECORD: "PAYOUT_RECORD",
  PAYOUT_PREPARE: "PAYOUT_PREPARE",
  PAYOUT_SKIP_DEFER: "PAYOUT_SKIP_DEFER",
  PAYOUT_SWAP: "PAYOUT_SWAP",
  PAYOUT_CONFIRM: "PAYOUT_CONFIRM",
  PAYOUT_ISSUE: "PAYOUT_ISSUE",

  // Feed / Events / Polls
  FEED_POST: "FEED_POST",
  FEED_DELETE: "FEED_DELETE",
  FEED_PIN: "FEED_PIN",
  EVENT_MANAGE: "EVENT_MANAGE",
  POLL_MANAGE: "POLL_MANAGE",

  // Join requests
  JOIN_REQUEST_REVIEW: "JOIN_REQUEST_REVIEW",

  // Invites
  INVITE_MANAGE: "INVITE_MANAGE",

  // Automations / Workflow
  AUTOMATION_MANAGE: "AUTOMATION_MANAGE",
  WORKFLOW_MANAGE: "WORKFLOW_MANAGE",

  // Approval workflows
  APPROVAL_WORKFLOW_VIEW: "APPROVAL_WORKFLOW_VIEW",
  APPROVAL_WORKFLOW_CREATE: "APPROVAL_WORKFLOW_CREATE",
  APPROVAL_WORKFLOW_UPDATE: "APPROVAL_WORKFLOW_UPDATE",
  APPROVAL_WORKFLOW_ACTIVATE: "APPROVAL_WORKFLOW_ACTIVATE",
  APPROVAL_WORKFLOW_ARCHIVE: "APPROVAL_WORKFLOW_ARCHIVE",

  // Approvals
  APPROVAL_REVIEW_OWN: "APPROVAL_REVIEW_OWN",
  APPROVAL_REVIEW_ANY: "APPROVAL_REVIEW_ANY",
  APPROVAL_DELEGATE: "APPROVAL_DELEGATE",
  APPROVAL_ESCALATE: "APPROVAL_ESCALATE",
  APPROVAL_VIEW_ALL: "APPROVAL_VIEW_ALL",

  // Constitution / Rules
  CONSTITUTION_VIEW: "CONSTITUTION_VIEW",
  CONSTITUTION_MANAGE: "CONSTITUTION_MANAGE",
  CONSTITUTION_PUBLISH: "CONSTITUTION_PUBLISH",
  CONSTITUTION_ACCEPTANCE_VIEW: "CONSTITUTION_ACCEPTANCE_VIEW",
  CONSTITUTION_AMEND: "CONSTITUTION_AMEND",
  CONSTITUTION_CONFLICT_RESOLVE: "CONSTITUTION_CONFLICT_RESOLVE",

  // Meetings
  MEETING_VIEW: "MEETING_VIEW",
  MEETING_CREATE: "MEETING_CREATE",
  MEETING_MANAGE: "MEETING_MANAGE",
  MEETING_CHECK_IN: "MEETING_CHECK_IN",
  MEETING_ATTENDANCE_MANAGE: "MEETING_ATTENDANCE_MANAGE",
  MEETING_MINUTES_MANAGE: "MEETING_MINUTES_MANAGE",
  MEETING_MINUTES_PUBLISH: "MEETING_MINUTES_PUBLISH",

  // Governance / Voting
  GOVERNANCE_VOTE: "GOVERNANCE_VOTE",
  GOVERNANCE_VOTE_VIEW: "GOVERNANCE_VOTE_VIEW",
  GOVERNANCE_VOTE_MANAGE: "GOVERNANCE_VOTE_MANAGE",
  GOVERNANCE_RESULT_VIEW: "GOVERNANCE_RESULT_VIEW",
} as const

export type CirclePermission =
  (typeof CIRCLE_PERMISSIONS)[keyof typeof CIRCLE_PERMISSIONS]

export const ALL_CIRCLE_PERMISSIONS: CirclePermission[] = Object.values(
  CIRCLE_PERMISSIONS
)
