export const CIRCLE_PERMISSIONS = {
  // Circle management
  CIRCLE_VIEW: "CIRCLE_VIEW",
  CIRCLE_UPDATE: "CIRCLE_UPDATE",
  CIRCLE_DELETE: "CIRCLE_DELETE",
  SETTINGS_MANAGE: "SETTINGS_MANAGE",

  // Member management
  MEMBER_VIEW: "MEMBER_VIEW",
  MEMBER_INVITE: "MEMBER_INVITE",
  MEMBER_REMOVE: "MEMBER_REMOVE",
  MEMBER_ROLE_UPDATE: "MEMBER_ROLE_UPDATE",
  MEMBER_PERMISSION_MANAGE: "MEMBER_PERMISSION_MANAGE",

  // Contributions
  CONTRIBUTION_CREATE: "CONTRIBUTION_CREATE",
  CONTRIBUTION_SUBMIT_OWN: "CONTRIBUTION_SUBMIT_OWN",
  CONTRIBUTION_VIEW_OWN: "CONTRIBUTION_VIEW_OWN",
  CONTRIBUTION_VIEW_ALL: "CONTRIBUTION_VIEW_ALL",
  CONTRIBUTION_REVIEW: "CONTRIBUTION_REVIEW",
  CONTRIBUTION_REJECT: "CONTRIBUTION_REJECT",
  CONTRIBUTION_REFUND: "CONTRIBUTION_REFUND",

  // Expenses
  EXPENSE_CREATE: "EXPENSE_CREATE",
  EXPENSE_VIEW: "EXPENSE_VIEW",
  EXPENSE_APPROVE: "EXPENSE_APPROVE",
  EXPENSE_DELETE: "EXPENSE_DELETE",

  // Settlements
  SETTLEMENT_CREATE: "SETTLEMENT_CREATE",
  SETTLEMENT_VIEW: "SETTLEMENT_VIEW",
  SETTLEMENT_CONFIRM: "SETTLEMENT_CONFIRM",

  // Goals
  GOAL_CREATE: "GOAL_CREATE",
  GOAL_UPDATE: "GOAL_UPDATE",
  GOAL_DELETE: "GOAL_DELETE",

  // Ledger
  LEDGER_VIEW: "LEDGER_VIEW",
  LEDGER_ADJUST: "LEDGER_ADJUST",

  // Reports
  REPORT_VIEW: "REPORT_VIEW",
  REPORT_EXPORT: "REPORT_EXPORT",

  // Projects
  PROJECT_CREATE: "PROJECT_CREATE",
  PROJECT_VIEW: "PROJECT_VIEW",
  PROJECT_MANAGE: "PROJECT_MANAGE",
  PROJECT_APPROVE: "PROJECT_APPROVE",

  // Project Funding
  FUNDING_ROUND_CREATE: "FUNDING_ROUND_CREATE",
  FUNDING_ALLOCATION_MANAGE: "FUNDING_ALLOCATION_MANAGE",
  FUNDING_RECORD: "FUNDING_RECORD",
  SHORTFALL_MANAGE: "SHORTFALL_MANAGE",
  INVESTOR_MANAGE: "INVESTOR_MANAGE",
  OWNERSHIP_VIEW: "OWNERSHIP_VIEW",
  OWNERSHIP_MANAGE: "OWNERSHIP_MANAGE",
  REVENUE_MANAGE: "REVENUE_MANAGE",
  DISTRIBUTION_CREATE: "DISTRIBUTION_CREATE",
  DISTRIBUTION_APPROVE: "DISTRIBUTION_APPROVE",

  // Wallets / Payouts
  WALLET_VIEW: "WALLET_VIEW",
  PAYOUT_REQUEST: "PAYOUT_REQUEST",
  PAYOUT_APPROVE: "PAYOUT_APPROVE",

  // Feed / Events / Polls
  FEED_POST: "FEED_POST",
  FEED_DELETE: "FEED_DELETE",
  FEED_PIN: "FEED_PIN",
  EVENT_MANAGE: "EVENT_MANAGE",
  POLL_MANAGE: "POLL_MANAGE",

  // Join requests
  JOIN_REQUEST_REVIEW: "JOIN_REQUEST_REVIEW",

  // Invites
  INVITE_MANAGE: "INVITE_MANAGE",

  // Automations / Workflow
  AUTOMATION_MANAGE: "AUTOMATION_MANAGE",
  WORKFLOW_MANAGE: "WORKFLOW_MANAGE",

  // Approval workflows
  APPROVAL_WORKFLOW_VIEW: "APPROVAL_WORKFLOW_VIEW",
  APPROVAL_WORKFLOW_CREATE: "APPROVAL_WORKFLOW_CREATE",
  APPROVAL_WORKFLOW_UPDATE: "APPROVAL_WORKFLOW_UPDATE",
  APPROVAL_WORKFLOW_ACTIVATE: "APPROVAL_WORKFLOW_ACTIVATE",
  APPROVAL_WORKFLOW_ARCHIVE: "APPROVAL_WORKFLOW_ARCHIVE",

  // Approvals
  APPROVAL_REVIEW_OWN: "APPROVAL_REVIEW_OWN",
  APPROVAL_REVIEW_ANY: "APPROVAL_REVIEW_ANY",
  APPROVAL_DELEGATE: "APPROVAL_DELEGATE",
  APPROVAL_ESCALATE: "APPROVAL_ESCALATE",
  APPROVAL_VIEW_ALL: "APPROVAL_VIEW_ALL",
} as const

export type CirclePermission =
  (typeof CIRCLE_PERMISSIONS)[keyof typeof CIRCLE_PERMISSIONS]

export const ALL_CIRCLE_PERMISSIONS: CirclePermission[] = Object.values(
  CIRCLE_PERMISSIONS
)
