import PDFDocument from "pdfkit"
import { CURRENCIES, APP_NAME } from "@/lib/constants"

export interface TravelStatementPdfData {
  circleName: string
  tripName: string
  destination: string | null
  startDate: string | null
  endDate: string | null
  memberName: string
  currency: string
  totals: {
    totalSpent: number
    totalContributions: number
    perPersonCost: number
    variance: number
    remainingFunds: number
  }
  row: {
    contributions: number
    memberPaidExpenses: number
    share: number
    settledGiven: number
    settledReceived: number
    refundAvailable: number
    finalBalance: number
  }
}

function symbol(code: string): string {
  return CURRENCIES.find((c) => c.code === code)?.symbol ?? code
}
function fmt(n: number, code: string): string {
  return `${symbol(code)}${(Number(n) || 0).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
}

export async function generateTravelStatementPdf(data: TravelStatementPdfData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 45, bufferPages: true, info: { Title: `Trip Statement — ${data.tripName}`, Author: APP_NAME } })
    const chunks: Buffer[] = []
    doc.on("data", (c: Buffer) => chunks.push(c))
    doc.on("end", () => resolve(Buffer.concat(chunks)))
    doc.on("error", reject)

    const w = doc.page.width - 90
    let y = 45
    const head = (t: string, size: number, bold: boolean, color = "#111827") => doc.fontSize(size).font(bold ? "Helvetica-Bold" : "Helvetica").fillColor(color).text(t, 45, y, { width: w, align: "center" })
    head(APP_NAME, 22, true); y += 26
    head("Final Trip Statement", 13, false, "#6b7280"); y += 16
    head(`${data.tripName}${data.destination ? ` — ${data.destination}` : ""}`, 10, false, "#374151"); y += 13
    head(`${data.memberName}${data.startDate ? ` · ${new Date(data.startDate).toDateString()}${data.endDate ? ` – ${new Date(data.endDate).toDateString()}` : ""}` : ""}`, 9, false, "#6b7280"); y += 20

    doc.strokeColor("#e5e7eb").lineWidth(1).roundedRect(45, y, w, 118, 4).stroke(); y += 10
    const items = [
      ["Total trip cost", fmt(data.totals.totalSpent, data.currency)],
      ["Per-person cost", fmt(data.totals.perPersonCost, data.currency)],
      ["Total contributions", fmt(data.totals.totalContributions, data.currency)],
      ["Budget variance", fmt(data.totals.variance, data.currency)],
      ["Remaining funds", fmt(data.totals.remainingFunds, data.currency)],
      ["Final balance", fmt(data.row.finalBalance, data.currency)],
    ]
    for (let i = 0; i < 6; i++) {
      const col = i % 3
      const x = 50 + col * (w / 3)
      doc.fontSize(8).font("Helvetica").fillColor("#6b7280").text(items[i][0], x, y, { width: w / 3 - 8, align: "center" })
      doc.fontSize(12).font("Helvetica-Bold").fillColor("#111827").text(items[i][1], x, y + 14, { width: w / 3 - 8, align: "center" })
      doc.moveTo(55 + (col + 1) * (w / 3), y).lineTo(55 + (col + 1) * (w / 3), y + 60).strokeColor("#e5e7eb").lineWidth(0.5).stroke()
    }
    y += 78
    doc.fontSize(8).font("Helvetica").fillColor("#6b7280").text(`Refund available: ${fmt(data.row.refundAvailable, data.currency)}`, 45, y, { width: w }); y += 16

    doc.fontSize(11).font("Helvetica-Bold").fillColor("#111827").text("Your contributions & positions", 45, y); y += 16
    const rows = [
      ["Contributions", fmt(data.row.contributions, data.currency)],
      ["Expenses paid", fmt(data.row.memberPaidExpenses, data.currency)],
      ["Expense share", fmt(data.row.share, data.currency)],
      ["Settled received", fmt(data.row.settledReceived, data.currency)],
      ["Settled given", fmt(data.row.settledGiven, data.currency)],
    ]
    doc.fontSize(8).font("Helvetica-Bold").fillColor("#374151")
    // two-column layout
    let yy = y + 14
    for (let i = 0; i < rows.length; i++) {
      const column = Math.floor(i / 3) // 0 or 1
      const sub = i % 3
      const x = 45 + column * 180
      if (i === 3) yy = y + 14
      if (sub === 0) yy = y + 14
      doc.font("Helvetica").fillColor("#374151").fontSize(9).text(rows[i][0], x, yy, { width: 120 })
      doc.font("Helvetica-Bold").text(rows[i][1], x + 120, yy, { width: 60, align: "right" })
      yy += 16
    }
    y += 80

    y += 15
    doc.strokeColor("#e5e7eb").lineWidth(1).moveTo(45, y).lineTo(45 + w, y).stroke(); y += 12
    doc.fontSize(8).font("Helvetica").fillColor("#9ca3af").text(`Generated by ${APP_NAME} · Final Statement · ${new Date().toISOString().slice(0, 10)}`, 45, y, { width: w, align: "center" })

    const range = doc.bufferedPageRange()
    for (let i = range.start; i < range.start + range.count; i++) {
      doc.switchToPage(i)
      doc.fontSize(8).font("Helvetica").fillColor("#9ca3af").text(`Page ${i - range.start + 1} of ${range.count} — ${APP_NAME}`, 45, doc.page.height - 35, { width: w, align: "center" })
    }
    doc.end()
  })
}